// Automatically generated by astro-icon
// 93713b7c8049c6f1f457c394c7d76cc3d1ee47b9a8e5223b2a2710aa7bf1f80a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "close"
		| "email"
		| "github"
		| "linkedin"
		| "menu"
		| "moon"
		| "sun"
		| "telegram";
}